version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: GitHub package registry login
          command: |
            echo "$DEPLOYMENT_PASSWORD" | docker login -u "$DEPLOYMENT_USERNAME" --password-stdin docker.pkg.github.com
      - run:
          name: Checkout CI scripts
          command: |
            git clone https://github.com/navikt/github-apps-support.git
            git clone https://github.com/navikt/sosialhjelp-ci.git
            echo "export PATH=\"`pwd`/github-apps-support/bin:`pwd`/sosialhjelp-ci/bin:$PATH\"" >> $BASH_ENV
      - run:
          name: Generate version number and docker image tags
          command: |
            VERSION=$(create-artifact-version.sh)
            echo "export DOCKER_TAG=\"docker.pkg.github.com/navikt/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> $BASH_ENV
      - run:
          name: Bygger Docker image
          command:
            docker build -t $DOCKER_TAG .
      - run:
          name: Create tag and release
          command: |
            echo $DIGISOS_KEY | tr '_' '\n' > digisos.key
            GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh digisos.key $DIGISOS_APPID`)
            rm digisos.key

            create-github-release.sh -p $CIRCLE_PROJECT_REPONAME -t $(create-artifact-version.sh) \
            -c $CIRCLE_SHA1 -m "$(format-commit-message.sh)" -a $GH_TOKEN
      - run:
          name: Pusher Docker image
          command: |
            echo $DOCKER_TAG
            docker push $DOCKER_TAG

  deploy_heroku:
    docker:
      - image: alpine/git
    steps:
      - checkout
      - run:
          name: Deploy on Heroku
          command: |
            # HEROKU_USERNAME must be URL encoded, eg. joachim.liepelt%40nav.no
            git remote add heroku https://$HEROKU_USERNAME:$HEROKU_AUTH_TOKEN@git.heroku.com/$CIRCLE_PROJECT_REPONAME.git
            git push heroku $CIRCLE_BRANCH:master --force

  browser-test:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: Run browser tests
          command: |
            set -eo pipefail
            git clone https://github.com/navikt/sosialhjelp-tester.git
            cd sosialhjelp-tester

            npm install
            npm run saucelabs-soknad

      - store_test_results:
          path: /tmp/test-results

  deploy_miljo:
    docker:
      - image: navikt/deployment-cli:0.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til miljø=${MILJO} i dev-sbs
          command: |
            git clone https://github.com/navikt/sosialhjelp-ci.git
            VERSION=$(sosialhjelp-ci/bin/create-artifact-version.sh)

            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-soknad --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/dev/${MILJO}.json

  deploy_miljo_tag:
    docker:
      - image: navikt/deployment-cli:0.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til miljø=${MILJO} i dev-sbs
          command: |
            deployment-cli deploy create --cluster=dev-sbs --repository=navikt/sosialhjelp-soknad --team=digisos -r=nais.yaml --var version=${TAG} --vars=nais/dev/${MILJO}.json

  deploy_prod:
    docker:
      - image: navikt/deployment-cli:0.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til prod
          command: |
            git clone https://github.com/navikt/sosialhjelp-ci.git
            VERSION=$(sosialhjelp-ci/bin/create-artifact-version.sh)

            deployment-cli deploy create --cluster=prod-sbs --repository=navikt/sosialhjelp-soknad --team=digisos -r=nais.yaml --var version=${VERSION} --vars=nais/prod/default.json

  deploy_prod_tag:
    docker:
      - image: navikt/deployment-cli:0.4.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy versjon=${VERSION} til prod
          command: |
            deployment-cli deploy create --cluster=prod-sbs --repository=navikt/sosialhjelp-soknad --team=digisos -r=nais.yaml --var version=${TAG} --vars=nais/prod/default.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_heroku:
          filters:
            branches:
              only: master
#      - browser-test:
#          requires:
#            - deploy_heroku

