name: Deploy til dev
on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil (uten .json) som skal deployes'
        required: true
        default: 'dev-sbs-intern'
      cluster:
        description: 'Cluster Ã¥ deploye til (dev-sbs, labs-gcp eller dev-gcp)'
        required: true
        default: 'dev-sbs'
  repository_dispatch:
    types: [deploy_dev_gcp, deploy_miljo_tag]

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Sett env variabler
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      - name: Sett cluster og config fra repository_dispatch
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "CLUSTER_NAME=${{ github.event.client_payload.cluster }}" >> $GITHUB_ENV
          echo "CONFIG_FILE=${{ github.event.client_payload.config-file-name }}" >> $GITHUB_ENV
      - name: Sett cluster og config fra workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "CLUSTER_NAME=${{ github.event.inputs.cluster }}" >> $GITHUB_ENV
          echo "CONFIG_FILE=${{ github.event.inputs.config-file-name }}" >> $GITHUB_ENV
      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais.yaml
          CLUSTER: ${{ env.CLUSTER_NAME }}
          VARS: nais/dev/${{ env.CONFIG_FILE }}.json
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}
