name: Heroku
on:
  push:
    branches:
      - master

jobs:
  deploy-heroku:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy on Heroku
        run: |
          PROJECT_NAME=sosialhjelp-soknad
          heroku container:login
          heroku container:push --recursive -a $PROJECT_NAME
          heroku container:release web -a $PROJECT_NAME
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
