name: Nattlig restart
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  deploy_dev-sbs:
    uses: navikt/sosialhjelp-soknad/.github/workflows/build_and_deploy_dev.yml@master
    with:
      config-file-name: dev-sbs
      cluster: dev-sbs
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  deploy_dev-sbs-intern:
    uses: navikt/sosialhjelp-soknad/.github/workflows/build_and_deploy_dev.yml@master
    with:
      config-file-name: dev-sbs-intern
      cluster: dev-sbs
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  deploy_dev-gcp:
    uses: navikt/sosialhjelp-soknad/.github/workflows/build_and_deploy_dev.yml@master
    with:
      config-file-name: dev
      cluster: dev-gcp
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  deploy_dev-gcp-mock:
    uses: navikt/sosialhjelp-soknad/.github/workflows/build_and_deploy_dev.yml@master
    with:
      config-file-name: mock
      cluster: dev-gcp
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  deploy_labs-gcp:
    uses: navikt/sosialhjelp-soknad/.github/workflows/build_and_deploy_dev.yml@master
    with:
      config-file-name: labs-gcp
      cluster: labs-gcp
    secrets:
      api_deploy_token: ${{ secrets.NAIS_DEPLOY_APIKEY }}